// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1617336321);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1617339561);
user_pref("app.update.lastUpdateTime.region-update-timer", 1617336580);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1617336081);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1617336201);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1617336460);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a8e0dd3e-e976-4309-8bbf-40ad6cde67c0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "[\"DuckDuckGo Lite\",\"Searx\",\"StartPage\",\"Qwant\",\"MetaGer\"]");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.cdn.mozilla.net/user-media/addons/607454/ublock_origin-1.34.0-an+fx.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.region.update.first-seen", 1617336581);
user_pref("browser.region.update.region", "HU");
user_pref("browser.region.update.updated", 1617336581);
user_pref("browser.slowStartup.averageTime", 1253);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.lastColdStartupCheck", 1617339008);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[\"ublock0_raymondhill_net-browser-action\",\"addon_darkreader_org-browser-action\",\"pywalfox_frewacom_org-browser-action\",\"_74145f27-f039-47ce-a470-a662b129930a_-browser-action\",\"sponsorblocker_ajay_app-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"urlbar-container\",\"fxa-toolbar-menu-button\",\"jid1-kkzogwgsw3ao4q_jetpack-browser-action\",\"adnauseam_rednoise_org-browser-action\",\"_60f82f00-9ad5-4de5-b31c-b16a47c51558_-browser-action\",\"vim-vixen_i-beam_org-browser-action\",\"cookiemaster_stroppykitten_com-browser-action\",\"ff2mpv_yossarian_net-browser-action\",\"keepassxc-browser_keepassxc_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\",\"addon_darkreader_org-browser-action\",\"pywalfox_frewacom_org-browser-action\",\"vim-vixen_i-beam_org-browser-action\",\"sponsorblocker_ajay_app-browser-action\",\"_74145f27-f039-47ce-a470-a662b129930a_-browser-action\",\"jid1-kkzogwgsw3ao4q_jetpack-browser-action\",\"adnauseam_rednoise_org-browser-action\",\"_60f82f00-9ad5-4de5-b31c-b16a47c51558_-browser-action\",\"cookiemaster_stroppykitten_com-browser-action\",\"ff2mpv_yossarian_net-browser-action\",\"keepassxc-browser_keepassxc_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"widget-overflow-fixed-list\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":16,\"newElementCount\":15}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("devtools.debugger.prefs-schema-version", 11);
user_pref("devtools.toolbox.selectedTool", "styleeditor");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.iniFile.exists.appversion", "87.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.librewolf-community.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210324131913");
user_pref("extensions.lastAppVersion", "87.0");
user_pref("extensions.lastPlatformVersion", "87.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.adnauseam@rednoise.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.cookiemaster@stroppykitten.com", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-KKzOGWgsW3Ao4Q@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.keepassxc-browser@keepassxc.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.librefox.http.watcher@intika.be", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.pywalfox@frewacom.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.sponsorBlocker@ajay.app", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.vim-vixen@i-beam.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{74145f27-f039-47ce-a470-a662b129930a}", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"17d14467-eaa8-4a43-ac4a-326efee52652\",\"screenshots@mozilla.org\":\"58e62bb6-e1df-42dc-bc5d-c29059cfff4c\",\"default-theme@mozilla.org\":\"2214462f-eda9-4168-8a0b-b808bbf91ce0\",\"google@search.mozilla.org\":\"5ef0373d-b871-4c3b-928b-acced9e34290\",\"amazondotcom@search.mozilla.org\":\"2ee9a2fa-1e88-4152-9d42-14c3723eb6c9\",\"wikipedia@search.mozilla.org\":\"84913353-0c06-48a5-9e5c-561c4347b911\",\"bing@search.mozilla.org\":\"e2c2c2e8-957f-440a-9089-47d621b2d8d5\",\"ddg@search.mozilla.org\":\"1081a7d0-3e98-4d55-94e3-c28ae5958d9b\",\"ebay@search.mozilla.org\":\"b1e4c495-364a-42e2-ae05-9da3099243ee\",\"addon@darkreader.org\":\"cdf2e304-709a-4bdf-a622-60691b1806c5\",\"pywalfox@frewacom.org\":\"108197c5-466b-428b-b72b-155ed25e65c2\",\"vim-vixen@i-beam.org\":\"83919075-5a37-453a-8340-c3584c8f1c05\",\"firefox-compact-dark@mozilla.org\":\"046127a7-35c8-4bb6-beaa-fdf96da29c05\",\"sponsorBlocker@ajay.app\":\"d10735ca-fa68-4e00-840b-c6062f328bff\",\"{74145f27-f039-47ce-a470-a662b129930a}\":\"8cbfd0e9-3c61-435a-bc15-74cf732fb9c0\",\"jid1-KKzOGWgsW3Ao4Q@jetpack\":\"d65ae14c-96e2-4864-8a58-a8f94421cff3\",\"adnauseam@rednoise.org\":\"daf7d587-3b5c-4730-a95d-b388400a0e43\",\"cookiemaster@stroppykitten.com\":\"a540275c-b7f1-4f7b-8566-0d8a6e755c74\",\"librefox.http.watcher@intika.be\":\"93d97e02-d97a-45f2-ac85-b0b520c01aa5\",\"ff2mpv@yossarian.net\":\"10c9f9d8-d675-411d-b3c2-49ec332d8bea\",\"keepassxc-browser@keepassxc.org\":\"67eb02c4-8a19-42b6-af20-e7722be51a45\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1617336019);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("identity.sendtabpromo.url", "");
user_pref("layout.spellcheckDefault", 0);
user_pref("media.gmp-manager.buildID", "20210324131913");
user_pref("media.gmp-manager.lastCheck", 1617335998);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.peerconnection.ice.proxy_only_if_behind_proxy", true);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"shutdown\",\"itemsToClear\":[\"cache\",\"cookies\",\"offlineApps\",\"history\",\"formdata\",\"downloads\",\"sessions\"],\"options\":{}},{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "2973f482-1369-426e-8ad2-f111b3aaa56e");
user_pref("security.sandbox.plugin.tempDirSuffix", "1bb32dbc-cb4d-41dc-b499-502f780f5c35");
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.management.page.breachAlertUrl", "");
user_pref("signon.management.page.mobileAndroidURL", "");
user_pref("signon.management.page.mobileAppleURL", "");
user_pref("startup.homepage_override_url", "about:blank");
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("toolkit.startup.last_success", 1617339006);
user_pref("toolkit.telemetry.cachedClientID", "b0971ca4-beec-438a-82a3-9405e1318178");
user_pref("ui.systemUsesDarkTheme", 1);
