#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

. "${HOME}/.cache/wal/colors.sh"


# sudo not required for some system commands
for x in mount umount sv pacman updatedb su cryptsetup reboot poweroff; do
	alias $x="sudo $x"
done

alias sudo="doas"
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"

# Recompiles all suckless stuff
refr() {
    pushd .
    for d in {dwm,st,slstatus,slock,dmenu}
        do cd ~/.config/$d && sudo make clean install
    done
    popd
}

# Sets wallpaper, compiles colorscheme and recompiles suckless stuff
# If no wallpaper was given, it resets to
setwallpaper() {
    WALLPAPER=~/.config/wallpaper.jpg
    [ -z $1 ] || cp $1 $WALLPAPER
    wal -c
    wal -n -i $WALLPAPER &&
    xwallpaper --zoom $WALLPAPER &&
    refr &&
    xdotool key "super+shift+r"
}

tmnt() {
    sudo cryptsetup open $1 crypt
    sudo mount /dev/mapper/crypt /mnt/
}

tumnt() {
    sudo umount /mnt
    sudo cryptsetup close crypt
}

dfs () {
    [ $# -eq 0 ] && dotfiles status || dotfiles $@
}

alias \
  dfsa="dotfiles add" \
  dfsc="dotfiles commit" \
  dfsac="dotfiles add $1 && dotfiles commit" \
  dfsp="dotfiles push" \
  dfspl="dotfiles pull" \
  dfsd="dotfiles diff" \
  dfsr="dotfiles restore" \
  dfsrs="dotfiles restore --staged"

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkdir="mkdir -pv" \
    yt="ytfzf -lt" \
    yts="ytfzf -st" \

# DMENU_COLORS="-nb \"$color0\" -nf \"$color15\" -sb \"$color2\" -sf \"$color15\""
# DISPLAY_WIDTH="$(expr $(xrandr | grep "*" | grep -oP "[0-9]+(?=x)") - 20)"
# DMENU_SIZE="-x 10 -y 10 -z $DISPLAY_WIDTH -h 20"
# alias \
#     dmenu_run_pretty="dmenu_run $DMENU_COLORS $DMENU_SIZE" \
#     dmenu="dmenu $DMENU_COLORS $DMENU_SIZE"

# Colorize commands when possible.
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    sdn="sudo shutdown -h now" \
    e="$EDITOR" \
    v="$EDITOR" \
    p="sudo pacman" \
    z="zathura" \
    rs="ka sxhkd ; sxhkd" \
    p="sudo pacman" \
    a="paru" \
    mc="make clean" \
    smci="sudo make clean install" \
    gma="gcc -lm main.c && ./a.out" \
    jf="jftui"

alias \
    g="git" \
    gs="git status" \
    ga="git add" \
    gc="git commit" \
    gac="git add -A && git commit" \
    gr="git restore" \
    gra="git restore ." \
    gd="git diff" \
    gp="git push" \
    gpl="git pull"

alias \
    ns="npm start" \
    nd="npm dev" \
    ni="npm install"

alias cal="cal 2021"

alias \
    s="cd ~/sync" \
    vw="cd ~/sync/vimwiki" \
    dl="cd ~/dl" \
    dc="cd ~/docs" \
    r="cd ~/repos" \
    w="cd ~/sync/háttérképek"

alias \
    cf="configfzf" \
    sf="scriptfzf" \
    pf="projectfzf"

function tk() { trans "$*" }
function tm() { trans -t 'en+de' "$*" }
