#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

. "${HOME}/.cache/wal/colors.sh"


# sudo not required for some system commands
for x in mount umount sv pacman updatedb su ; do
	alias $x="sudo $x"
done

alias sudo="doas"
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"

# Recompiles all suckless stuff
refr() {
    pushd .
    for d in {dwm,st,slstatus,slock,dmenu}
    do cd ~/.config/$d && sudo make clean install
    done
    popd
}

setwallpaper() {
    cp $1 ~/.config/wallpaper.jpg
    wal -c
    wal -n -i ~/.config/wallpaper.jpg
    xwallpaper --zoom ~/.config/wallpaper.jpg
    refr
    xdotool key "super+shift+r"
}

dfs () {
    [ $# -eq 0 ] && dotfiles status || dotfiles $@
}

alias \
  dfsa="dotfiles add" \
  dfsc="dotfiles commit" \
  dfsac="dotfiles add && dotfiles commit" \
  dfsp="dotfiles push" \
  dfspl="dotfiles pull" \
  dfsd="dotfiles diff" \
  dfsr="dotfiles restore"

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkd="mkdir -pv" \
    yt="ytfzf -lt" \
    yts="yt -S" \
    mpv="mpv --fs"

# DMENU_COLORS="-nb \"$color0\" -nf \"$color15\" -sb \"$color2\" -sf \"$color15\""
# DISPLAY_WIDTH="$(expr $(xrandr | grep "*" | grep -oP "[0-9]+(?=x)") - 20)"
# DMENU_SIZE="-x 10 -y 10 -z $DISPLAY_WIDTH -h 20"
# alias \
#     dmenu_run_pretty="dmenu_run $DMENU_COLORS $DMENU_SIZE" \
#     dmenu="dmenu $DMENU_COLORS $DMENU_SIZE"

# Colorize commands when possible.
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    sdn="sudo shutdown -h now" \
    e="$EDITOR" \
    v="$EDITOR" \
    p="sudo pacman" \
    z="zathura" \
    rs="ka sxhkd ; sxhkd" \
    p="sudo pacman" \
    a="paru" \
    mc="make clean" \
    smci="sudo make clean install" \
    gma="gcc main.c && ./a.out" \
    jf="jftui"

alias \
    cst="cd ~/.config/st" \
    cdwm="cd ~/.config/dwm" \
    cslock="cd ~/.config/slock" \
    cdmenu="cd ~/.config/dmenu" \
    cslstatus="cd ~/.config/slstatus"

alias \
    cv="$EDITOR ~/.config/nvim/init.vim" \
    cb="$EDITOR ~/.bashrc" \
    cz="$EDITOR ~/.config/zsh/.zshrc" \
    czp="$EDITOR ~/.zprofile" \
    cs="$EDITOR ~/.config/sxhkd/sxhkdrc" \
    cx="$EDITOR ~/.xinitrc" \
    ca="$EDITOR ~/.config/aliasrc" \
    cl="$EDITOR ~/.config/lf/lfrc" \
    cc="$EDITOR ~/.config/picom/picom.conf" \
    cnc="$EDITOR ~/.config/newsboat/config" \
    cnu="$EDITOR ~/.config/newsboat/urls" \
    cm="$EDITOR ~/.config/mpv/mpv.conf" \
    cf="$EDITOR ~/.mozilla/firefox/*/chrome/userChrome.css" \
    cpk="$EDITOR ~/.config/pkgs"

alias \
    g="git" \
    gs="git status" \
    ga="git add" \
    gc="git commit" \
    gac="git add -A && git commit" \
    gr="git restore" \
    gra="git restore ." \
    gd="git diff" \
    gp="git push"

alias \
    ns="npm start" \
    nd="npm dev" \
    ni="npm install"

alias cal="cal 2021"

alias \
    s="cd ~/sync" \
    vw="cd ~/sync/vimwiki" \
    dl="cd ~/dl" \
    dc="cd ~/docs" \
    r="cd ~/repos" \
    w="cd ~/sync/háttérképek"
