#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

. "${HOME}/.cache/wal/colors.sh"


# sudo not required for some system commands
for x in mount umount sv pacman updatedb su cryptsetup reboot poweroff; do
	alias $x="sudo $x"
done

alias sudo="doas"
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"

# Recompiles all suckless stuff
refr() {
    pushd .
    for d in {dwm,st,slstatus,slock,dmenu}
        do cd ~/.config/$d && sudo make clean install
    done
    popd
}

# Sets wallpaper, compiles colorscheme and recompiles suckless stuff
# If no wallpaper was given, it resets to
setwallpaper() {
    WALLPAPER=~/.config/wallpaper.jpg
    [ -z $1 ] || cp $1 $WALLPAPER
    wal -c
    wal -n -i $WALLPAPER &&
    xwallpaper --zoom $WALLPAPER &&
    refr &&
    xdotool key "super+shift+r"
}

# mount encrypted drive
tmnt() {
    sudo cryptsetup open \
        $(lsblk -rpo "name,size,type,mountpoint" | \
            awk '{if ($NF == "part") print $1, $2}' | \
            fzf --color=bw --reverse --prompt="Select partition to mount > " | \
            cut -d" " -f1) \
        crypt
    sudo mount /dev/mapper/crypt /mnt/
}

tumnt() {
    sudo umount /mnt
    sudo cryptsetup close crypt
}

# dfs shortcut
dfs () {
    [ $# -eq 0 ] && dotfiles status || dotfiles $@
}

alias \
  dfsa="dotfiles add" \
  dfsc="dotfiles commit" \
  dfsac="dotfiles add $1 && dotfiles commit" \
  dfsp="dotfiles push" \
  dfspl="dotfiles pull" \
  dfsd="dotfiles diff" \
  dfsr="dotfiles restore" \
  dfsrs="dotfiles restore --staged"

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkdir="mkdir -pv" \
    yt="ytfzf -lt" \
    yts="ytfzf -st" \
    cal="cal $(date +'%Y')"

# Colorize commands when possible.
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    sdn="sudo shutdown -h now" \
    e="$EDITOR" \
    v="$EDITOR" \
    p="sudo pacman" \
    z="zathura" \
    rs="ka sxhkd ; sxhkd &" \
    p="sudo pacman" \
    a="paru" \
    mc="make clean" \
    smci="sudo make clean install" \
    gma="gcc -lm main.c && ./a.out" \
    jf="jftui" \
    nt="ping 1.1.1.1" \

# git abbreviations
alias \
    g="git" \
    gs="git status" \
    ga="git add" \
    gc="git commit" \
    gac="git add -A && git commit" \
    gr="git restore" \
    gra="git restore ." \
    gd="git diff" \
    gp="git push" \
    gpl="git pull"

# npm abbreviations
alias \
    ns="npm start" \
    nd="npm dev" \
    ni="npm install"

# dir shortcuts
alias \
    s="cd ~/sync" \
    vw="cd ~/sync/vimwiki" \
    dl="cd ~/dl" \
    dc="cd ~/docs" \
    r="cd ~/repos" \
    w="cd ~/sync/háttérképek" \
    or="cd ~/sync/org" \

# custom fzf scripts
alias \
    cf="configfzf" \
    sf="scriptfzf" \
    pf="projectfzf" \
    strf="streamfzf"

# translation
function tk() { trans "$*" }
function tm() { trans -t 'en+de' "$*" }

# curl websites shortcut
alias \
    weather="curl wttr.in"

function cheat() { curl "cheat.sh/$*" }
function dict() { curl "dict://dict.org/d:$*" }
function fileshare() { curl -sF"file=@$*" https://0x0.st | xclip -sel clip && echo "$(xclip -o -sel clip) copied" }
